#!/bin/bash

export DOCKERFILE_PATH="${DOCKERFILE_PATH:-Dockerfile}"
export DOCKER_REPO="${DOCKER_REPO:-cycloid/cycloid-toolkit}"
export DOCKER_TAG="${DOCKER_TAG:-develop}"

echo "# Received : $SOURCE_COMMIT"

IFS=$'\n'
for line in $(cat .versions); do
    python_version=$(echo $line | awk '{print $1}')
    ansible_version=$(echo $line | awk '{print $2}')
    tag=$(echo $line | awk '{print $3}')
    if [[ "$tag" == "default_tag" ]]; then
        tag=$DOCKER_TAG
    fi
    extra_tags=$(echo "$line" | awk -F " " '{for(i=4;i<=NF;++i)printf " -t '$DOCKER_REPO':"$i}')
    echo $extra_tags
    echo "=> Building $tag"
    eval docker build --build-arg PYTHON_VERSION=$python_version --build-arg ANSIBLE_VERSION=$ansible_version -f $DOCKERFILE_PATH -t $DOCKER_REPO:$tag $extra_tags .
done
unset IFS
