#!/bin/bash

export DOCKERFILE_PATH="${DOCKERFILE_PATH:-Dockerfile}"

echo "# Received : $SOURCE_COMMIT"

echo "=> Building latest"
docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .

IFS=$'\n'
for line in $(cat .ansible_versions); do
    version=${line% *}
    tag=v${line#* }
    echo "=> Building $tag"
    sed -i "s/ansible==.*/ansible==${version}/" requirements.txt
    docker build -f $DOCKERFILE_PATH -t $DOCKER_REPO:$tag .
done
unset IFS
