#!/bin/sh

usage()
{
    echo "You should provide the following env vars :"
    echo ""
    echo "$0"
    echo "  * AWS_ACCESS_KEY_ID"
    echo "  * AWS_SECRET_ACCESS_KEY"
    echo "  * BASTION_PRIVATE_KEY"
    echo "  * BASTION_URL"
    echo "  * ANSIBLE_VAULT_PASSWORD"
    echo "  * (TAGS)"
    echo "  * (SKIP_TAGS)"
    echo "  * (EXTRA_ARGS)"
    echo "  * (EXTRA_VARS) as a json dict."
    echo "  * (ANSIBLE_PLAYBOOK_NAME) default : site.yml"
    echo "  * (ANSIBLE_PLAYBOOK_PATH) default : ansible-playbook"
    echo "  * (ANSIBLE_REMOTE_USER) default : admin"
    echo ""
    exit 1
}
if [ -n "$1" ]; then usage; fi

# Set defaults
export ANSIBLE_PLAYBOOK_PATH="${ANSIBLE_PLAYBOOK_PATH:-ansible-playbook}"
export ANSIBLE_PLAYBOOK_NAME="${ANSIBLE_PLAYBOOK_NAME:-site.yml}"
export ANSIBLE_REMOTE_USER="${ANSIBLE_REMOTE_USER:-admin}"

# Check args
if [ -z "$AWS_ACCESS_KEY_ID" ] ||
[ -z "$AWS_SECRET_ACCESS_KEY" ] ||
[ -z "$BASTION_PRIVATE_KEY" ] ||
[ -z "$BASTION_URL" ] ||
[ -z "$ANSIBLE_VAULT_PASSWORD" ]; then
usage
fi

# Construct vars
if [ -n "$EXTRA_VARS" ]; then
  EXTRA_ARGS="${EXTRA_ARGS} $(echo $EXTRA_VARS | jq -r 'to_entries[] | "-e \(.key)=\(.value | .)"' | tr '\n' ' ')"
fi
if [ -n "$TAGS" ]; then
  EXTRA_ARGS="${EXTRA_ARGS} --tags $(echo $TAGS | jq -r '. | join(",")')"
fi
if [ -n "$SKIP_TAGS" ]; then
  EXTRA_ARGS="${EXTRA_ARGS} --skip-tags $(echo $SKIP_TAGS | jq -r '. | join(",")')"
fi

# Setup ssh access
echo "${BASTION_PRIVATE_KEY}" > /root/.ssh/id_rsa
chmod 600  /root/.ssh/id_rsa
echo ${ANSIBLE_VAULT_PASSWORD} > $ANSIBLE_PLAYBOOK_PATH/.vault-password
#export DEFAULT_VAULT_PASSWORD_FILE="$ANSIBLE_PLAYBOOK_PATH/.vault-password"

set -xe

export ANSIBLE_FORCE_COLOR=true
export ANSIBLE_SSH_ARGS='-o ProxyCommand="ssh -W %h:%p -q '${BASTION_URL}'"'
#echo "ansible_ssh_common_args: '-o ProxyCommand=\"ssh -W %h:%p -q ${BASTION_URL}\"'" >> $ANSIBLE_PLAYBOOK_PATH/group_vars/all

cd $ANSIBLE_PLAYBOOK_PATH

if [ -f "requirements.yml" ]; then
    ansible-galaxy install -r requirements.yml --roles-path=roles -v
fi
ansible-playbook -u $ANSIBLE_REMOTE_USER --vault-password-file=.vault-password $ANSIBLE_PLAYBOOK_NAME --diff ${EXTRA_ARGS}
exit $?
