#!/bin/sh

usage()
{
    echo "You should provide the following env vars :"
    echo ""
    echo "$0"
    echo "  * AWS_ACCESS_KEY_ID"
    echo "  * AWS_SECRET_ACCESS_KEY"
    echo "  * AWS_NAME_PATTERNS: Array of pattern of AMI name."
    echo "  * (AWS_DEFAULT_REGION)"
    echo "  * (KEEP): how many old version of the ami to keep. default 1"
    echo ""
    exit 1

}
if [ -n "$1" ]; then usage; fi

# Set defaults
export TERM=linux
export TERMINFO=/etc/terminfo
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-eu-west-1}"
export KEEP="${KEEP:-1}"


# Check args
if [ -z "$AWS_ACCESS_KEY_ID" ] ||
[ -z "$AWS_SECRET_ACCESS_KEY" ] ||
[ -z "$AWS_NAME_PATTERNS" ]; then
usage
fi

set -xe

# Convert json array to a string
for PATTERN in $(echo $AWS_NAME_PATTERNS | jq -r '. | join(" ")'); do
    amicleaner -f --mapping-key name --mapping-values ${PATTERN} --keep-previous ${KEEP} --full-report
done
exit $?
