#!/bin/sh

usage()
{
    echo "You should provide the following env vars :"
    echo ""
    echo "$0"
    echo "  * STACK_PATH"
    echo "  * CONFIG_PATH"
    echo "# _SUB_PATH refer to the root path of git. Expecting something like :"
    echo "# CONFIG_PATH = ((project))/ansible or ((project))/terraform/((env)"
    echo "# STACK_PATH = stack-((project))/ansible or stack-((project))/terraform"
    echo ""
    echo "  * (TERRAFORM_METADATA_FILE). Default lookup terraform/metadata. If find, will add vars into group_vars/all (input directory should be provided for ansible stack only)"
    echo "  * (STACK_ROOT_PATH). Expect to have git input named stack."
    echo "  * (CONFIG_ROOT_PATH). Default look for a git input named config."
    echo "  * (MERGE_OUTPUT_PATH). Default merged-stack."
    echo ""
    exit 1
}


if [ -n "$1" ]; then usage; fi

# Set defaults
export MERGE_OUTPUT_PATH="${MERGE_OUTPUT_PATH:-merged-stack}"
export STACK_ROOT_PATH="${STACK_ROOT_PATH:-stack}"
export CONFIG_ROOT_PATH="${CONFIG_ROOT_PATH:-config}"
export TERRAFORM_METADATA_FILE="${TERRAFORM_METADATA_FILE:-terraform/metadata}"

# Check args
if [ -z "$STACK_PATH" ] ||
[ -z "$CONFIG_PATH" ]; then
usage
fi

set -e

echo "############ Merging : ${STACK_ROOT_PATH}/${STACK_PATH}/ <- ${CONFIG_ROOT_PATH}/${CONFIG_PATH}/"

rsync -av ${STACK_ROOT_PATH}/${STACK_PATH}/ $MERGE_OUTPUT_PATH/
if [ -d "${CONFIG_ROOT_PATH}/${CONFIG_PATH}" ]; then
  rsync -av ${CONFIG_ROOT_PATH}/${CONFIG_PATH}/ $MERGE_OUTPUT_PATH/
fi

# In case of ansible run, we might have provided terraform output metadata file.
# Lookup if we are in this case. And generate those vars for ansible. 
if [ -f "$TERRAFORM_METADATA_FILE" ]; then
  echo "############ Extracting Terraform output -> group_vars/all extract-terraform-outputs"
  OUTPUT_ANSIBLE_VAR_FILE=${MERGE_OUTPUT_PATH}/group_vars/all extract-terraform-outputs
fi

echo "############ extract tag for the image : <stack_id>-<config_id>"
echo "$(git --git-dir=$STACK_ROOT_PATH/.git rev-parse --verify HEAD --short)-$(git --git-dir=$CONFIG_ROOT_PATH/.git rev-parse --verify HEAD --short)" | tee $MERGE_OUTPUT_PATH/tag

exit $?
